### PR TITLE
added maven wrapper files to root project 

### PR DESCRIPTION
**Pull request by salemraffa**

### CODE REVIEW

**Review by astanik — CHANGES_REQUESTED** [review]
@salemraffa Your maven wrapper looks very good! However, can you please update the README.md as well?

**Review by basselali97 — APPROVED** [review]

**Comment by astanik** [comment]
@salemraffa Can you please respond to my review?

**Comment by salemraffa** [comment]
will do !

**Comment by salemraffa** [comment]
in my project they are updated but it seems I can't push them. Maybe because im on another branch ?

**Review by astanik — APPROVED** [review]
Good job!

**Pull request merged**
